channels:
  - conda-forge
  - genepattern
  - r
dependencies:
  - matplotlib
  - numpy
  - pandas
  - rise
  - jupyter_contrib_nbextensions
  - jupyter-wysiwyg  
  - r-irkernel
  - r-tidyverse
  - r-tidymodels
  
